### ISSUE TITLE
'Piperi' is an option for lunch

### ISSUE THREAD

**Issue by ZackBoyd** [ysnikitin/funch#2]
I disagree with this option.

**Comment by mderoche** [comment]
wontfix

**Comment by ZackBoyd** [comment]
I appreciate the response time

**Comment by ysnikitin** [comment]
@ZackBoyd you might be interested in the far superior fork - https://github.com/ysnikitin/funchWithoutPiperi. Please take a look and see if it suits your needs.

**Comment by ToreyStapleton** [comment]
@ysnikitin  that solves my issue, thanks!!

**Comment by ZackBoyd** [comment]
Funch2 is best Funch

**Comment by ZackBoyd** [comment]
Thanks!
