### ISSUE TITLE
It is unclear who is on Funch for any given week, resulting in dereliction of duty

### ISSUE THREAD

**Issue by ZackBoyd** [ysnikitin/funch#3]
or worse, Piperi! 

The people demand a page in Funch that:

- Displays upcoming Funch duty roster, including date and assignees sorting in chronological order according to the Gregorian calendar
- Past Funch dates should be hidden to users!
- Allows admins to **inline edit** assignees and select from a strict list of EI employees for re-assignment
- Reflects approved EI branding guidelines
- Has a user setting to display all results in Papyrus
- Gives the user an intuitive experience
- Infinite scroll list

You have one week.

**Comment by ysnikitin** [comment]
Pull request or GTFO, I'm not spending my Reddit-ing time at work to fix this.
